# Use an official Python runtime as a parent image
FROM python:3.9

# Set the working directory in the container
WORKDIR /usr/src/app

# Install FastAPI and Uvicorn
RUN pip install fastapi uvicorn

# Install Robot Framework
RUN pip install robotframework

# Copy the current directory contents into the container at /usr/src/app
COPY . /usr/src/app

# Make port 8000 available to the world outside this container
EXPOSE 8000

# Define environment variable
ENV MODULE_NAME="main"
ENV VARIABLE_NAME="app"

# Run main.py when the container launches
CMD ["uvicorn", "$MODULE_NAME:$VARIABLE_NAME", "--host", "0.0.0.0", "--port", "8000"]
